# Generated by Django 5.1.3 on 2024-11-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='mood',
            field=models.CharField(choices=[('M', 'Moody'), ('H', 'Happy'), ('E', 'Ecstatic'), ('G', 'Grumpy'), ('P', 'Peaceful')], default='H', max_length=1),
        ),
    ]
