# Generated by Django 5.1.3 on 2024-11-12 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_cat_mood_alter_feeding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Feeding Date'),
        ),
    ]
